// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserSubscriptionManagement.Infrastructure.Entities;

[Table("admin_types")]
[Index("AdminType", Name = "UQ__admin_ty__922F88DA2E6A404F", IsUnique = true)]
public partial class AdminTypes
{
    [Key]
    [Column("id")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Required]
    [Column("admin_type")]
    [StringLength(255)]
    [Unicode(false)]
    public string AdminType { get; set; }

    [InverseProperty("AdminType")]
    public virtual ICollection<Users> Users { get; set; } = new List<Users>();
}