// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserSubscriptionManagement.Infrastructure.Entities;

[Table("users")]
[Index("Username", Name = "UQ__users__F3DBC5723E98249D", IsUnique = true)]
public partial class Users
{
    [Key]
    [Column("id")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Column("profile_id")]
    public int? ProfileId { get; set; }

    [Required]
    [Column("username")]
    [StringLength(255)]
    [Unicode(false)]
    public string Username { get; set; }

    [Required]
    [Column("password_hash")]
    [StringLength(255)]
    [Unicode(false)]
    public string PasswordHash { get; set; }

    [Column("admin_type_id")]
    public int? AdminTypeId { get; set; }

    [Column("balance")]
    public double Balance { get; set; }

    [Required]
    [Column("is_enabled")]
    public bool? IsEnabled { get; set; }

    [ForeignKey("AdminTypeId")]
    [InverseProperty("Users")]
    public virtual AdminTypes AdminType { get; set; }

    [ForeignKey("ProfileId")]
    [InverseProperty("Users")]
    public virtual UsersProfile Profile { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<UserSubscriptions> UserSubscriptions { get; set; } = new List<UserSubscriptions>();
}