// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserSubscriptionManagement.Infrastructure.Entities;

[Table("users_profile")]
public partial class UsersProfile
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("email")]
    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [Column("first_name")]
    [StringLength(255)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [Required]
    [Column("last_name")]
    [StringLength(255)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Column("middle_name")]
    [StringLength(255)]
    [Unicode(false)]
    public string MiddleName { get; set; }

    [Required]
    [Column("address")]
    [StringLength(255)]
    [Unicode(false)]
    public string Address { get; set; }

    [Required]
    [Column("phone")]
    [StringLength(255)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Required]
    [Column("zip")]
    [StringLength(255)]
    [Unicode(false)]
    public string Zip { get; set; }

    [InverseProperty("Profile")]
    public virtual ICollection<Users> Users { get; set; } = new List<Users>();
}