// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UserSubscriptionManagement.Infrastructure.Entities;

[PrimaryKey("UserId", "SubscriptionId")]
[Table("user_subscriptions")]
public partial class UserSubscriptions
{
    [Key]
    [Column("user_id")]
    public int UserId { get; set; }

    [Key]
    [Column("subscription_id")]
    public int SubscriptionId { get; set; }

    [Column("start_date", TypeName = "date")]
    public DateTime StartDate { get; set; }

    [ForeignKey("SubscriptionId")]
    [InverseProperty("UserSubscriptions")]
    public virtual Subscriptions Subscription { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserSubscriptions")]
    public virtual Users User { get; set; }
}