// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using UserSubscriptionManagement.Infrastructure.Entities;

namespace UserSubscriptionManagement.Infrastructure.Database;

public partial class UserSubscriptionsManagementContext : DbContext
{
    public UserSubscriptionsManagementContext(DbContextOptions<UserSubscriptionsManagementContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AdminTypes> AdminTypes { get; set; }

    public virtual DbSet<Subscriptions> Subscriptions { get; set; }

    public virtual DbSet<UserSubscriptions> UserSubscriptions { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AdminTypes>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__admin_ty__3213E83F90FB8E82");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Subscriptions>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__subscrip__3213E83F95110DD0");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Duration).HasDefaultValueSql("((30))");
        });

        modelBuilder.Entity<UserSubscriptions>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.SubscriptionId }).HasName("PK__user_sub__B1DD90E349DA502C");

            entity.HasOne(d => d.Subscription).WithMany(p => p.UserSubscriptions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__user_subs__subsc__66603565");

            entity.HasOne(d => d.User).WithMany(p => p.UserSubscriptions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__user_subs__user___656C112C");
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__users__3213E83F4776E960");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.IsEnabled).HasDefaultValueSql("((1))");

            entity.HasOne(d => d.AdminType).WithMany(p => p.Users).HasConstraintName("FK__users__admin_typ__60A75C0F");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}